apiVersion: v1
kind: Service
metadata:
  name: users-service
  labels:
    app: users-server
spec:
  selector:
    app: users-server  
  type: LoadBalancer
  ports:
    - name: grpc
      protocol: TCP
      port: 7777
      targetPort: 7777
---
apiVersion: v1
kind: Service
metadata:
  name: idgen-service
  labels:
    app: users-server
spec:
  selector:
    app: idgen
  type: LoadBalancer     
  ports:
    - name: ws
      protocol: TCP
      port: 8080
      targetPort: 8080
