apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: users-server
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 7777
---     
apiVersion: v1
kind: Service
metadata:
  name: idgen-service
spec:
  selector:
    app: idgen
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 8080

