// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/proto/v1/user_service.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbe8950ff2a66fbd, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

type ListUsersRequest struct {
	// The parent resource name, for example, "shelves/shelf1"
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// The maximum number of items to return.
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// The next_page_token value returned from a previous List request, if any.
	PageToken            string   `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUsersRequest) Reset()         { *m = ListUsersRequest{} }
func (m *ListUsersRequest) String() string { return proto.CompactTextString(m) }
func (*ListUsersRequest) ProtoMessage()    {}
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbe8950ff2a66fbd, []int{1}
}

func (m *ListUsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersRequest.Unmarshal(m, b)
}
func (m *ListUsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersRequest.Marshal(b, m, deterministic)
}
func (m *ListUsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersRequest.Merge(m, src)
}
func (m *ListUsersRequest) XXX_Size() int {
	return xxx_messageInfo_ListUsersRequest.Size(m)
}
func (m *ListUsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersRequest proto.InternalMessageInfo

func (m *ListUsersRequest) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *ListUsersRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListUsersRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

type ListUsersResponse struct {
	// The field name should match the noun "User" in the method name.
	// There will be a maximum number of items returned based on the page_size field in the request.
	Users []*User `protobuf:"bytes,1,rep,name=Users,proto3" json:"Users,omitempty"`
	// Token to retrieve the next page of results, or empty if there are no more results in the list.
	NextPageToken        string   `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUsersResponse) Reset()         { *m = ListUsersResponse{} }
func (m *ListUsersResponse) String() string { return proto.CompactTextString(m) }
func (*ListUsersResponse) ProtoMessage()    {}
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbe8950ff2a66fbd, []int{2}
}

func (m *ListUsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersResponse.Unmarshal(m, b)
}
func (m *ListUsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersResponse.Marshal(b, m, deterministic)
}
func (m *ListUsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersResponse.Merge(m, src)
}
func (m *ListUsersResponse) XXX_Size() int {
	return xxx_messageInfo_ListUsersResponse.Size(m)
}
func (m *ListUsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersResponse proto.InternalMessageInfo

func (m *ListUsersResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *ListUsersResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "v1.User")
	proto.RegisterType((*ListUsersRequest)(nil), "v1.ListUsersRequest")
	proto.RegisterType((*ListUsersResponse)(nil), "v1.ListUsersResponse")
}

func init() {
	proto.RegisterFile("api/proto/v1/user_service.proto", fileDescriptor_cbe8950ff2a66fbd)
}

var fileDescriptor_cbe8950ff2a66fbd = []byte{
	// 280 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xcf, 0x4b, 0xf3, 0x40,
	0x10, 0x86, 0xbf, 0x24, 0x6d, 0x49, 0xa6, 0x7c, 0xfe, 0x58, 0x54, 0x82, 0xa2, 0x86, 0x1c, 0x24,
	0xa7, 0x84, 0xd4, 0x9b, 0x47, 0x6f, 0x82, 0x88, 0x6c, 0xf5, 0xa2, 0x87, 0xb0, 0xda, 0xa9, 0x2c,
	0xda, 0x24, 0xee, 0x6c, 0x83, 0xf4, 0xaf, 0x97, 0xd9, 0xb4, 0x52, 0x7a, 0xcc, 0xf3, 0x66, 0xdf,
	0x67, 0x66, 0xe0, 0x52, 0xb5, 0xba, 0x68, 0x4d, 0x63, 0x9b, 0xa2, 0x2b, 0x8b, 0x25, 0xa1, 0xa9,
	0x08, 0x4d, 0xa7, 0xdf, 0x31, 0x77, 0x54, 0xf8, 0x5d, 0x99, 0x4a, 0x18, 0x3c, 0x13, 0x1a, 0xb1,
	0x07, 0xbe, 0x9e, 0xc5, 0x5e, 0xe2, 0x65, 0x81, 0xf4, 0xf5, 0x4c, 0x9c, 0x03, 0xcc, 0xb5, 0x21,
	0x5b, 0xd5, 0x6a, 0x81, 0xb1, 0x9f, 0x78, 0x59, 0x24, 0x23, 0x47, 0x1e, 0xd4, 0x02, 0xc5, 0x19,
	0x44, 0x5f, 0x6a, 0x93, 0x06, 0x2e, 0x0d, 0x19, 0x70, 0x98, 0xce, 0xe1, 0xe0, 0x5e, 0x93, 0xe5,
	0x5e, 0x92, 0xf8, 0xbd, 0x44, 0xb2, 0xe2, 0x04, 0x46, 0xad, 0x32, 0x58, 0x5b, 0xe7, 0x88, 0xe4,
	0xfa, 0x8b, 0x8b, 0x5a, 0xf5, 0x81, 0x15, 0xe9, 0x55, 0xaf, 0x19, 0xca, 0x90, 0xc1, 0x54, 0xaf,
	0x90, 0x87, 0x70, 0xa1, 0x6d, 0x3e, 0xb1, 0x5e, 0x6b, 0xdc, 0xef, 0x4f, 0x0c, 0xd2, 0x57, 0x38,
	0xdc, 0xf2, 0x50, 0xdb, 0xd4, 0x84, 0xe2, 0x02, 0x86, 0x0e, 0xc4, 0x5e, 0x12, 0x64, 0xe3, 0x49,
	0x98, 0x77, 0x65, 0xce, 0x40, 0xf6, 0x58, 0x5c, 0xc1, 0x7e, 0x8d, 0x3f, 0xb6, 0xda, 0x2a, 0xee,
	0xb7, 0xfb, 0xcf, 0xf8, 0x71, 0x53, 0x3e, 0xb9, 0x83, 0x31, 0x3f, 0x98, 0xf6, 0x17, 0x13, 0x37,
	0x10, 0xfd, 0xb9, 0xc4, 0x11, 0x97, 0xee, 0xae, 0x78, 0x7a, 0xbc, 0x43, 0xfb, 0x81, 0xd2, 0x7f,
	0xb7, 0x83, 0x17, 0xbf, 0x2b, 0xdf, 0x46, 0xee, 0xe8, 0xd7, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x77, 0xf0, 0xb3, 0x62, 0x97, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	//*
	// Get users list
	ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error) {
	out := new(ListUsersResponse)
	err := c.cc.Invoke(ctx, "/v1.UserService/ListUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	//*
	// Get users list
	ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) ListUsers(ctx context.Context, req *ListUsersRequest) (*ListUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUsers not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.UserService/ListUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ListUsers(ctx, req.(*ListUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListUsers",
			Handler:    _UserService_ListUsers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/v1/user_service.proto",
}
